### PR TITLE
Node18upgrade

### PR DESCRIPTION
**Pull request by jcwatson11**

### CODE REVIEW

**Comment by jcwatson11** [comment]
@Omicron7 @wrandall22 This project doesn't appear to have a staging branch. Is that of any concern?

**Comment by Omicron7** [comment]
cc @frett See above

**Comment by frett** [comment]
no, because we don't have any staging infrastructure for this script that just unzips things from one bucket to another bucket

**Comment by frett** [comment]
we are in the process of eliminating the need for the bucket with the unzipped files, but we aren't quite there yet

**Review by wrandall22 — APPROVED** [review]

**Pull request merged**
